/*
	RAMAKE PROJECT : AGUSSAMP
	GM VERSION : 3.5
	DISCORD AGUSSAMP : https://discord.gg/M8AHY7VG5r
	DISCORD AGUSSAMP OFFCIAL : https://discordapp.com/servers/agussamp-community-1268554715336020082
	ALL GAMEMODE PRICE/HARGA : 40K
	PEMBAYARAAN : DANA, GOPAY, QRIS
*/
